// BillTypes.js
export const FETCH_BILL_REQUEST = 'FETCH_BILL_REQUEST';
export const FETCH_BILL_SUCCESS = 'FETCH_BILL_SUCCESS';
export const FETCH_BILL_ERROR = 'FETCH_BILL_ERROR';

export const FETCH_SEARCH_BILL_REQUEST = 'FETCH_SEARCH_BILL_REQUEST';

export const ADD_BILL_REQUEST = 'ADD_BILL_REQUEST';
export const ADD_BILL_SUCCESS = 'ADD_BILL_SUCCESS';
export const ADD_BILL_ERROR = 'ADD_BILL_ERROR';

export const UPDATE_BILL_REQUEST = 'UPDATE_BILL_REQUEST';
export const UPDATE_BILL_SUCCESS = 'UPDATE_BILL_SUCCESS';
export const UPDATE_BILL_ERROR = 'UPDATE_BILL_ERROR';

export const DELETE_BILL_REQUEST = 'DELETE_BILL_REQUEST';
export const DELETE_BILL_SUCCESS = 'DELETE_BILL_SUCCESS';
export const DELETE_BILL_ERROR = 'DELETE_BILL_ERROR';
