// Constants for Bill Details
export const FETCH_BILL_DETAILS_REQUEST = 'FETCH_BILL_DETAILS_REQUEST';
export const FETCH_BILL_DETAILS_SUCCESS = 'FETCH_BILL_DETAILS_SUCCESS';
export const FETCH_BILL_DETAILS_FAILURE = 'FETCH_BILL_DETAILS_FAILURE';
export const UPDATE_BILL_STATUS = 'UPDATE_BILL_STATUS';
export const COMPLETE_BILL = 'COMPLETE_BILL';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

// Constants for Bill Statistics
export const FETCH_BILL_STATISTICS_REQUEST = 'FETCH_BILL_STATISTICS_REQUEST';
export const FETCH_BILL_STATISTICS_SUCCESS = 'FETCH_BILL_STATISTICS_SUCCESS';
export const FETCH_BILL_STATISTICS_FAILURE = 'FETCH_BILL_STATISTICS_FAILURE';
